# Generated by Django 5.1.6 on 2025-03-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='q_groupings',
            field=models.JSONField(default=[[0, 0, 0, 0, 0, 0, 0, 0]]),
            preserve_default=False,
        ),
    ]
