# Generated by Django 5.2.11 on 2026-02-22 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmap', '0002_user_q_groupings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('num_var', models.IntegerField()),
                ('form', models.CharField(max_length=5)),
                ('terms', models.JSONField()),
                ('dont_cares', models.JSONField()),
                ('groupings', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='time_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='time_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DailyChallengeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('completion_time_seconds', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='kmap.dailychallenge')),
            ],
            options={
                'ordering': ['completion_time_seconds'],
                'unique_together': {('username', 'daily_challenge')},
            },
        ),
    ]
