# Generated by Django 5.1.6 on 2026-02-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmap', '0003_dailychallenge_user_time_completed_user_time_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailychallengeresult',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
