# Generated by Django 5.1.6 on 2026-02-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmap', '0004_dailychallengeresult_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeAttackResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')])),
                ('questions_solved', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-questions_solved', 'created_at'],
            },
        ),
    ]
